### ISSUE TITLE
Throws 500 error when trying to use

### ISSUE THREAD

**Issue by JoelSParker** [digwood/Shiphero#4]
When I try to use any of the functions it throws a 500 error. I have installed it using composer but also tried to directly include the files.

**Comment by JoelSParker** [comment]
I was able to get it working by using includes directly to the files, but not with composer's autoload

**Comment by mdeschermeier** [comment]
Thanks for the heads up, Joel. Things are starting to calm down enough that I can focus more attention back on this. I'll take a look at the namespacing and JSON file and make sure everything is set correctly.

**Comment by mdeschermeier** [comment]
I was able to finally carve out some time to look into this, and it appears that the namespacing and PSR-4 autoloading are functioning correctly. If anyone else is having a similar problem, please create another issue and be sure to include any error messages you get.

**Comment by JoelSParker** [comment]
Maybe this will help...

Here is my code:
![image](https://cloud.githubusercontent.com/assets/6782101/23168203/5b1dde6c-f815-11e6-87ec-b912083f7635.png)

And the error that is thrown:
"Fatal error: Uncaught Error: Class 'Shiphero' not found in E:\MAMP\htdocs\dh-ibbh-shiphero-integration\generate-shiphero-order.php:13 Stack trace: #0 {main} thrown in E:\MAMP\htdocs\dh-ibbh-shiphero-integration\generate-shiphero-order.php on line 13"

If I require the file directly everything works fine.

**Comment by mdeschermeier** [comment]
Ah, I think I see the issue. The class is namespaced, so you will need to use the namespace to access the class. Take a look at the snippet below: 

```
<?php
require_once "vendor/autoload.php";
use mdeschermeier\shiphero\Shiphero; // <--- Be sure to include this line!

Shiphero::setkey('<INSERT KEY HERE>');
Shiphero::verifyPeer(false);
$resp = Shiphero::getProduct(array('page' => 1));
var_dump($resp);

 ?>
```

If it's still not loading, be sure to let me know and I'll take a deeper look. Otherwise, let me know that it did the trick and I'll update the Readme.
